### ISSUE TITLE
Digital Twins shape needs a review

### ISSUE THREAD

**Issue by pradyharish** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#20]
The shape seems to have a size issue. Can be fixed by user after dragging too (by ungrouping), but still something that can be fixed at the source I'm guessing.

<img width="1134" alt="GithubIssueForDigitalTwinShapeInVisioStencil" src="https://user-images.githubusercontent.com/52256949/82237504-9783fc00-98ea-11ea-82ff-31726d9aea12.png">

**Comment by Crossbow78** [comment]
I believe all icon elements in this stencil pack are too easily dragged out of their container.
When you click any icon twice, you'll notice that an _element_ within the icon gets selected, and subsequently dragged or resized. Also, connector lines will snap to individual icon elements, instead of anchor points.
![image](https://user-images.githubusercontent.com/7549753/86588930-f0881c00-bf8c-11ea-8226-ac49c53c9ee6.png)
Most other icon stencils (eg. from Microsoft) seem to have some 'shape protection' enabled to keep their icon elements grouped together.

The icons in this stencil pack are absolutely beautiful and it's such complete set, but the (1) element editing, (2) missing connector points, and (3) missing text labels, make them practically unusable.

**Comment by sandroasp** [comment]
Hi Crossbow78,

You are correct and it is how it should work because all of these shapes are vectorial shapes fully resizable without losing quality, they are not pictures.

regarding "connector lines will snap to individual icon elements, instead of the whole icon or explicit anchor points", I'm fixing that at the moment

**Comment by sandroasp** [comment]
Hi pradyharish,

fixed and improve Digital Twins shape
